services:
    phpbbstudio.pdf.listener:
        class: \phpbbstudio\pdf\event\listener
        arguments:
            - '@language'
            - '%core.root_path%'
        tags:
            - { name: event.listener }
